CREATE TABLE PUBLIC.USER_LIST (
	IDX BIGINT NOT NULL AUTO_INCREMENT,
	GROUP_IDX BIGINT NOT NULL,
	USER_ID VARCHAR(10000) NOT NULL,
	PASSWARD VARCHAR(10000) NOT NULL,
	USER_NAME VARCHAR(10000) NOT NULL,
	EMAIL VARCHAR(10000),
	ADDRESS VARCHAR(10000),
	PHONE VARCHAR(10000) NOT NULL,
	OPTIONS VARCHAR(10000),
	CREATE_DTTM VARCHAR(10000),
	UPDATE_DTTM VARCHAR(10000),
	CONSTRAINT USER_LIST_PK PRIMARY KEY (IDX)
);
COMMENT ON TABLE PUBLIC.USER_LIST IS '사용자 정보 테이블';
COMMENT ON COLUMN PUBLIC.USER_LIST.IDX IS 'index';
COMMENT ON COLUMN PUBLIC.USER_LIST.GROUP_IDX IS '사용자 그룹 index';
COMMENT ON COLUMN PUBLIC.USER_LIST.USER_ID IS '사용자 ID';
COMMENT ON COLUMN PUBLIC.USER_LIST.PASSWARD IS '패스워드';
COMMENT ON COLUMN PUBLIC.USER_LIST.USER_NAME IS '사용자 이름';
COMMENT ON COLUMN PUBLIC.USER_LIST.EMAIL IS '이메일 주소';
COMMENT ON COLUMN PUBLIC.USER_LIST.ADDRESS IS '주소지';
COMMENT ON COLUMN PUBLIC.USER_LIST.PHONE IS '휴대폰 번호';
COMMENT ON COLUMN PUBLIC.USER_LIST.OPTIONS IS 'options 태그';
COMMENT ON COLUMN PUBLIC.USER_LIST.CREATE_DTTM IS '생성일';
COMMENT ON COLUMN PUBLIC.USER_LIST.UPDATE_DTTM IS '수정일';




CREATE TABLE PUBLIC.USER_GROUP_INFO (
	IDX BIGINT NOT NULL AUTO_INCREMENT,
	AUTHORITY VARCHAR(10000) NOT NULL,
	OPTIONS VARCHAR(10000),
	CREATE_DTTM VARCHAR(10000),
	UPDATE_DTTM VARCHAR(10000),
	CONSTRAINT USER_GROUP_INFO_PK PRIMARY KEY (IDX)
);
COMMENT ON TABLE PUBLIC.USER_GROUP_INFO IS '사용자 권한 그룹 정보 테이블';
COMMENT ON COLUMN PUBLIC.USER_GROUP_INFO.IDX IS 'index';
COMMENT ON COLUMN PUBLIC.USER_GROUP_INFO.AUTHORITY IS '사용자 권한 이름';
COMMENT ON COLUMN PUBLIC.USER_GROUP_INFO.OPTIONS IS 'options 태그';
COMMENT ON COLUMN PUBLIC.USER_GROUP_INFO.CREATE_DTTM IS '생성일';
COMMENT ON COLUMN PUBLIC.USER_GROUP_INFO.UPDATE_DTTM IS '수정일';



CREATE TABLE PUBLIC.POINT_SUMMARY (
	IDX BIGINT NOT NULL AUTO_INCREMENT,
	USER_IDX BIGINT NOT NULL,
	NOW_POINT VARCHAR(10000) NOT NULL,
	OPTIONS VARCHAR(10000),
	CREATE_DTTM VARCHAR(10000),
	UPDATE_DTTM VARCHAR(10000),
	CONSTRAINT POINT_SUMMARY_PK PRIMARY KEY (IDX)
);
COMMENT ON TABLE PUBLIC.POINT_SUMMARY IS '적립금 현황 테이블';
COMMENT ON COLUMN PUBLIC.POINT_SUMMARY.IDX IS 'index';
COMMENT ON COLUMN PUBLIC.POINT_SUMMARY.USER_IDX IS '사용자_IDX';
COMMENT ON COLUMN PUBLIC.POINT_SUMMARY.NOW_POINT IS '현재 적립금';
COMMENT ON COLUMN PUBLIC.POINT_SUMMARY.OPTIONS IS 'options 태그';
COMMENT ON COLUMN PUBLIC.POINT_SUMMARY.CREATE_DTTM IS '생성일';
COMMENT ON COLUMN PUBLIC.POINT_SUMMARY.UPDATE_DTTM IS '수정일';



CREATE TABLE PUBLIC.POINT_EVENT (
	IDX BIGINT NOT NULL AUTO_INCREMENT,
	USER_IDX BIGINT NOT NULL,
	STATUS VARCHAR(10000) NOT NULL,
	POINT BIGINT NOT NULL,
	OPTIONS VARCHAR(10000),
	CREATE_DTTM VARCHAR(10000),
	UPDATE_DTTM VARCHAR(10000),
	EXPIRATION_DTTM VARCHAR(10000),
	CONSTRAINT POINT_EVENT_PK PRIMARY KEY (IDX)
);
COMMENT ON TABLE PUBLIC.POINT_EVENT IS '적립금 변경 이벤트 테이블';
COMMENT ON COLUMN PUBLIC.POINT_EVENT.IDX IS 'index';
COMMENT ON COLUMN PUBLIC.POINT_EVENT.USER_IDX IS '사용자 IDX';
COMMENT ON COLUMN PUBLIC.POINT_EVENT.STATUS IS '적립금 변경 상태';
COMMENT ON COLUMN PUBLIC.POINT_EVENT.POINT IS '적립금 변경 값';
COMMENT ON COLUMN PUBLIC.POINT_EVENT.OPTIONS IS 'options 태그';
COMMENT ON COLUMN PUBLIC.POINT_EVENT.CREATE_DTTM IS '생성일';
COMMENT ON COLUMN PUBLIC.POINT_EVENT.UPDATE_DTTM IS '수정일';
COMMENT ON COLUMN PUBLIC.POINT_EVENT.EXPIRATION_DTTM IS '포인트 만료일';



CREATE TABLE PUBLIC.POINT_EVENT_DETAIL (
	IDX BIGINT NOT NULL AUTO_INCREMENT,
	USER_IDX BIGINT NOT NULL,
	EVENT_IDX BIGINT NOT NULL,
	ORIGIN_EVENT_DETAIL_IDX BIGINT,
	STATUS VARCHAR(100) NOT NULL,
	POINT BIGINT NOT NULL,
	OPTIONS VARCHAR(100),
	CREATE_DTTM VARCHAR(100),
	UPDATE_DTTM VARCHAR(100),
	CONSTRAINT POINT_EVENT_DETAIL_PK PRIMARY KEY (IDX)
);
COMMENT ON TABLE PUBLIC.POINT_EVENT_DETAIL IS '적립금 변경 테이블에 발생한 이벤트의 세부 내역을 저장한 테이블';
COMMENT ON COLUMN PUBLIC.POINT_EVENT_DETAIL.IDX IS 'Index';
COMMENT ON COLUMN PUBLIC.POINT_EVENT_DETAIL.USER_IDX IS '사용자 idx';
COMMENT ON COLUMN PUBLIC.POINT_EVENT_DETAIL.EVENT_IDX IS '적립금 변경 이벤트 idx';
COMMENT ON COLUMN PUBLIC.POINT_EVENT_DETAIL.ORIGIN_EVENT_DETAIL_IDX IS '적립금 변경 세부 이벤트 idx';
COMMENT ON COLUMN PUBLIC.POINT_EVENT_DETAIL.STATUS IS '적립금 변경 상태';
COMMENT ON COLUMN PUBLIC.POINT_EVENT_DETAIL.POINT IS '적립금 변경 값';
COMMENT ON COLUMN PUBLIC.POINT_EVENT_DETAIL.OPTIONS IS 'options 태그';
COMMENT ON COLUMN PUBLIC.POINT_EVENT_DETAIL.CREATE_DTTM IS '생성일';
COMMENT ON COLUMN PUBLIC.POINT_EVENT_DETAIL.UPDATE_DTTM IS '수정일';
